# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: straight-server 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "straight-server"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roman Snitko"]
  s.date = "2015-01-07"
  s.description = "Accepts orders via http, returns payment info via http or streams updates via websockets, stores orders in a DB"
  s.email = "roman.snitko@gmail.com"
  s.executables = ["straight-console", "straight-server"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/straight-console",
    "bin/straight-server",
    "db/migrations/001_create_orders.rb",
    "db/migrations/002_create_gateways.rb",
    "examples/client/client.dart",
    "examples/client/client.html",
    "lib/straight-server.rb",
    "lib/straight-server/config.rb",
    "lib/straight-server/gateway.rb",
    "lib/straight-server/initializer.rb",
    "lib/straight-server/logger.rb",
    "lib/straight-server/order.rb",
    "lib/straight-server/orders_controller.rb",
    "lib/straight-server/server.rb",
    "lib/straight-server/thread.rb",
    "spec/.straight/config.yml",
    "spec/factories.rb",
    "spec/lib/gateway_spec.rb",
    "spec/lib/order_spec.rb",
    "spec/lib/orders_controller_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/custom_matchers.rb",
    "straight-server.gemspec",
    "templates/config.yml"
  ]
  s.homepage = "http://github.com/snitko/straight-server"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A Bitcoin payment gateway server: a state server for the stateless Straight library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<straight>, [">= 0"])
      s.add_runtime_dependency(%q<satoshi-unit>, [">= 0"])
      s.add_runtime_dependency(%q<goliath>, [">= 0"])
      s.add_runtime_dependency(%q<faye-websocket>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_runtime_dependency(%q<logmaster>, ["= 0.1.2"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<github_api>, ["= 0.11.3"])
    else
      s.add_dependency(%q<straight>, [">= 0"])
      s.add_dependency(%q<satoshi-unit>, [">= 0"])
      s.add_dependency(%q<goliath>, [">= 0"])
      s.add_dependency(%q<faye-websocket>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<logmaster>, ["= 0.1.2"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<github_api>, ["= 0.11.3"])
    end
  else
    s.add_dependency(%q<straight>, [">= 0"])
    s.add_dependency(%q<satoshi-unit>, [">= 0"])
    s.add_dependency(%q<goliath>, [">= 0"])
    s.add_dependency(%q<faye-websocket>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<logmaster>, ["= 0.1.2"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<github_api>, ["= 0.11.3"])
  end
end

